apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deployment
spec:
  selector:
    matchLabels:
      app: user-microservice-k8s-mysql
  replicas: 3
  template:
    metadata:
      labels:
        app: user-microservice-k8s-mysql
    spec:
      containers:
        - name: user-microservice-k8s
          image: insurancerepo.azurecr.io/insurancerepo:pipelineUser
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: user-microservice-svc
spec:
  selector:
    app: user-microservice-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.